name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:   
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@8.2
        with:
          dir: './src'
      - name: DEPLOY
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{secrets.HOST}} 
          user: ${{secrets.USERNAME}} 
          private_key: ${{secrets.KEY}} 
          command: |
            cd test-workflow &&
            git pull origin main
